// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://fsbwbjdnfytqigucuqbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzYndiamRuZnl0cWlndWN1cWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1OTQ4NjAsImV4cCI6MjA3ODE3MDg2MH0.IzVekXCiYpB0OsPNsMTNk43V0_kXA-Vdv89ODNNNMgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
